# LAB 1: Matrix and Vector Computations in python
In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Solving System of Linear Equations Using Gaussian Elimination.

- Matrix Multiplication using Different views.

# First: you should run this cell

In [27]:
# Make all numpy available via shorter 'np' prefix
import numpy as np
import sympy as sym

# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [28]:
#type your code here:
s = np.array(5)

v = np.array([ [5], [-2], [4] ])

A = np.array ([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]) 

B = np.array ([ [1, 2, 3], [4, 5, 6] ])

C = np.array ([ [1, 2], [3, 4], [5, 6] ])

print("s = ", s)
print("\nv = \n", v) 
print("\nA = \n", A)
print("\nB = \n", B)
print("\nC = \n", C)

s =  5

v = 
 [[ 5]
 [-2]
 [ 4]]

A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

B = 
 [[1 2 3]
 [4 5 6]]

C = 
 [[1 2]
 [3 4]
 [5 6]]


b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [29]:
#type your code here:
print("type(s) = ", type(s))
print("type(v) = ", type(v))
print("type(A) = ", type(A))

type(s) =  <class 'numpy.ndarray'>
type(v) =  <class 'numpy.ndarray'>
type(A) =  <class 'numpy.ndarray'>


c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [30]:
#type your code here:
print("s.shape = ", s.shape)
print("v.shape = ", v.shape)
print("A.shape = ", A.shape)
print("B.shape = ", B.shape)
print("C.shape = ", C.shape)

s.shape =  ()
v.shape =  (3, 1)
A.shape =  (3, 3)
B.shape =  (2, 3)
C.shape =  (3, 2)


d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [31]:
#type your code here:
print("A[2, 1] = ", A[2, 1])
A[2, 1] = 10
print("\nA = \n", A)

A[2, 1] =  8

A = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

In [32]:
#type your code here:
print("A[:, [1]] = \n", A[:, [1]])
print("\nB[[1], :] = \n", B[[1], :])

A[:, [1]] = 
 [[ 2]
 [ 5]
 [10]]

B[[1], :] = 
 [[4 5 6]]


f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [52]:
#type your code here:
print("np.eye(4) = \n", np.eye(4))
print("\nnp.zaeros(3) = \n", np.zeros(4))
print("\nnp.zeros(3, 1) = \n", np.zeros((3, 1)))
print("\nnp.zeros(3, 5) = \n", np.zeros((3, 5)))
print("\nnp.ones(2, 3) = \n", np.ones((2, 3)))
print("\nnp.diag([4, 5, 6, 7]) = \n", np.diag([4, 5, 6, 7]))

np.eye(4) = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.zaeros(3) = 
 [0. 0. 0. 0.]

np.zeros(3, 1) = 
 [[0.]
 [0.]
 [0.]]

np.zeros(3, 5) = 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

np.ones(2, 3) = 
 [[1. 1. 1.]
 [1. 1. 1.]]

np.diag([4, 5, 6, 7]) = 
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

In [34]:
#type your code here:
v1 = np.array([ [1], [2], [7], [4] ])
v2 = np.array([ [4], [3], [6], [8] ])

print("v1 = \n", v1)
print("\nv2 = \n", v2)
print("\nv1 + v2 = \n", v1 + v2)
print("\nv1 - v2 = \n", v1 - v2)
print("\n3 * v1 = \n", 3 * v1)
print("\nv1 / 2 = \n", v1 / 2)

v1 = 
 [[1]
 [2]
 [7]
 [4]]

v2 = 
 [[4]
 [3]
 [6]
 [8]]

v1 + v2 = 
 [[ 5]
 [ 5]
 [13]
 [12]]

v1 - v2 = 
 [[-3]
 [-1]
 [ 1]
 [-4]]

3 * v1 = 
 [[ 3]
 [ 6]
 [21]
 [12]]

v1 / 2 = 
 [[0.5]
 [1. ]
 [3.5]
 [2. ]]


b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [35]:
#type your code here:
print("Using numpy.dot = \n", np.dot(v1.T , v2))
print("\nUsing numpy.matmul = \n", np.matmul(v1.T , v2))
print("\nUsing @ = \n", v1.T @ v2)

Using numpy.dot = 
 [[84]]

Using numpy.matmul = 
 [[84]]

Using @ = 
 [[84]]


c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [36]:
#type your code here:
print("length of v1 Using numpy.linalg.norm = ")
print(np.linalg.norm(v1))
print("\nlength of v2 Using numpy.linalg.norm = ")
print(np.linalg.norm(v2))
print("\nlength of v1 Using the dot product and numpy.sqrt = ")
print(np.sqrt(v1.T @ v1))
print("\nlength of v2 Using the dot product and numpy.sqrt = ")
print(np.sqrt(v2.T @ v2))

length of v1 Using numpy.linalg.norm = 
8.366600265340756

length of v2 Using numpy.linalg.norm = 
11.180339887498949

length of v1 Using the dot product and numpy.sqrt = 
[[8.36660027]]

length of v2 Using the dot product and numpy.sqrt = 
[[11.18033989]]


d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [37]:
#type your code here:
u = np.array([ [3], [2], [-1], [4] ])
v = np.array([ [1], [-1], [1], [0] ])

print("u.T @ v = ")
print(u.T @ v)

u.T @ v = 
[[0]]


# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$
- $(3A^T)^T$

In [38]:
#type your code here:
u = np.array([ [2], [7], [2] ])
v = np.array([ [8], [2], [4] ])
A = np.array ([ [7, 3, 5], [4, 6, 2] ]) 
B = np.array ([ [0, 6, 4], [2, 3, 0] ]) 

print("u = \n", u)
print("\nv = \n", v)
print("\nA = \n", A)
print("\nB = \n", B)

print("\nA + B = \n", A + B)
print("\nB + A = \n", B + A)
print("\n3A = \n", (3 * A))
print("\n6B = \n", 6 * B)
print("\n2(3B) = \n", 2 * (3 * B))
print("\n6A + 15B = \n", (6 * A) + (15 * B))
print("\n3(2A + 5B) = \n", 3*((2 * A) + (5 * B)))
print("\n(3A^T)^T = \n", (3 * A.T).T)

u = 
 [[2]
 [7]
 [2]]

v = 
 [[8]
 [2]
 [4]]

A = 
 [[7 3 5]
 [4 6 2]]

B = 
 [[0 6 4]
 [2 3 0]]

A + B = 
 [[7 9 9]
 [6 9 2]]

B + A = 
 [[7 9 9]
 [6 9 2]]

3A = 
 [[21  9 15]
 [12 18  6]]

6B = 
 [[ 0 36 24]
 [12 18  0]]

2(3B) = 
 [[ 0 36 24]
 [12 18  0]]

6A + 15B = 
 [[ 42 108  90]
 [ 54  81  12]]

3(2A + 5B) = 
 [[ 42 108  90]
 [ 54  81  12]]

(3A^T)^T = 
 [[21  9 15]
 [12 18  6]]


b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [39]:
#type your code here:
print("Au + Av = \n", A @ u + A @ v)
print("\nA(u+v) = \n", A @ (u + v))
print("\n(A + B)u = \n", ((A + B) @ u))
print("\nAu + Bu = \n", A @ u + B @ u)
print("\nA(3u) = \n", A @ (3 * u))
print("\n3A(u) = \n", (3 * A) @ u)

Au + Av = 
 [[127]
 [106]]

A(u+v) = 
 [[127]
 [106]]

(A + B)u = 
 [[95]
 [79]]

Au + Bu = 
 [[95]
 [79]]

A(3u) = 
 [[135]
 [162]]

3A(u) = 
 [[135]
 [162]]


# Question 4. Gaussian Elimination and Reduced Row-Echelon Form

You will see a step-by-step example of the row operations that transform a matrix $A$ into its reduced row echelon form $R = rref(A)$. In this demonstration, each pivot is chosen to be the largest in its column (for numerical stability), so extra row interchanges are used. Since $rref(A)$ is uniquely determined by $A$, this does not affect the final answer.

The built in [rref](https://docs.sympy.org/latest/tutorial/matrices.html#rref) method `sympy.rref()` method just search for the method and its output to deal with the code.

#### (a) Generate and display a $3 \times 4$ matrix $A$ with random integer entries 

In [40]:
#type your code here:
A = np.fix((10*(np.random.rand(3,4))))
print("\n A = \n", A)


 A = 
 [[8. 6. 2. 1.]
 [8. 8. 1. 0.]
 [9. 9. 1. 1.]]


- To transform $A$ into $R = rref(A)$, start with $R = A$.
- Normalize the first row of R to get R(1st row, 1st column) = 1

    - `R = A`
    - `R[0,:] = R[0, :] / R[0, 0]`

(note the use of the colon to operate on whole rows of the matrix). 

<div class="alert alert-block alert-warning">If your random matrix happens to have A(1, 1) = 0, then interchange rows to get a nonzero entry in the (1, 1) position before doing the calculation above.</div>

- Now subtract a multiple of the first row of R from the second row to make R(2, 1) = 0:

    - `R[1, :] = R[1, :] - R[1, 0] * R[0, :]`

- Repeat this procedure to make R(3, 1) = 0:

    - `R[2, :] = R[2, :] - R[2, 0] * R[0, :]`

The first column of your matrix $R$ should now be the same as the first column of $rref(A)$.

In [41]:
#type your code here:
R = A
R[0,:] = R[0, :] / R[0, 0]
R[1, :] = R[1, :] - R[1, 0] * R[0, :]
R[2, :] = R[2, :] - R[2, 0] * R[0, :]
print("\nR = \n", R)


R = 
 [[ 1.     0.75   0.25   0.125]
 [ 0.     2.    -1.    -1.   ]
 [ 0.     2.25  -1.25  -0.125]]


#### (b)Operate on $R$ by the same method as in (a) to obtain the second column of $rref(A)$. First normalize row $2$ of $R$, then subtract multiples of row $2$ from rows $1$ and $3$ to put zeros in the (1, 2) and (3, 2) positions. Be sure to refer to the entries in your matrix symbolically as was done in part (a)

In [42]:
#type your code here:
R[1,:] = R[1, :] / R[1, 1]
R[0, :] = R[0, :] - R[0, 1] * R[1, :]
R[2, :] = R[2, :] - R[2, 1] * R[1, :]
print("\nR = \n", R)


R = 
 [[ 1.     0.     0.625  0.5  ]
 [ 0.     1.    -0.5   -0.5  ]
 [ 0.     0.    -0.125  1.   ]]


#### (c) Operate on $R$ by the same method as in (b) to obtain the third column of $rref(A)$. First normalize row $3$ of $R$, then subtract multiples of row $3$ from rows $1$ and $2$ to put zeros in the (1, 3) and (2, 3) positions.

In [43]:
#type your code here:
R[2,:] = R[2, :] / R[2, 2]
R[0, :] = R[0, :] - R[0, 2] * R[2, :]
R[1, :] = R[1, :] - R[1, 2] * R[2, :]
print("\nR = \n", R)


R = 
 [[ 1.   0.   0.   5.5]
 [ 0.   1.   0.  -4.5]
 [-0.  -0.   1.  -8. ]]


#### (d) Your matrix $R$ should now be transformed into $rref(A)$ (since $A$ is a random $3 \times 4$ matrix, $rref(A)$ is (almost) sure to have rank (3) `np.linalg.matrix_rank(R)`. Check your answer by python with the rref method . If the answer is not the same as the current value of your $R$, go back and redo your calculations.

- use the the built in rref method `sympy.rref()`
- print the output matrix in numpy array type

    - `M = sym.Matrix(A)`
    - `M_rref = M.rref()`
    - `R = np.array((M_rref[0])).astype(np.float64)`

In [44]:
#type your code here:
print("\nrank = \n",np.linalg.matrix_rank(R))
# Use sympy.rref() method 
M = sym.Matrix(A)
M_rref = M.rref()
R = np.array((M_rref[0])).astype(np.float64)
print("\nThe Row echelon form of matrix M \n", R)


rank = 
 3

The Row echelon form of matrix M 
 [[ 1.   0.   0.   5.5]
 [ 0.   1.   0.  -4.5]
 [ 0.   0.   1.  -8. ]]


# Question 5. Matrix Multiplication using Different views

we discussed in the lecture four different ways about product $AB = C$ where $A$ and $B$ are arbitry matrices. If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, then $C$ is an $m \times p$ matrix:

1. **Standard(row times column):** The standard way of describing a matrix product is to say that $c_(ij)$ equals the dot product of row $i$ of matrix $A$ and column $j$ of matrix $B$. 
 
2. **Columns:** The product of matrix $A$ and column $j$ of matrix $B$ equals column $j$ of matrix  $C$. This tells us that the columns of $C$ are combinations of columns of $A$.

3. **Rows:** The product of row $i$ of matrix $A$ and matrix $B$ equals row $i$ of matrix $C$.So the rows of $C$ are combinations of rows of $B$.

4. **Column times row**: A column of $A$ is an $m \times 1$ vector and a row of $B$ is a $1 \times p$ vector.Their product is a matrix.

In this problem we will use python to perform the matrix multiplication using these different ways, and compute the execution time for each method time.

(Write your code as a function that perform the multiplication for arbitrary size of the matrices $A$ and $B$)

In [45]:
def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    

    ########################################################        
    return C


def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    

    ########################################################         
    return C

def mat_mul_rows(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    

    ########################################################         
    return C



def mat_mul_column_times_row(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    

    ########################################################         
    return C

In [46]:
#A = np.array([[12., 7., 3.],[4., 5., 6.],[7., 8., 9.]])
#B = np.array([[5., 8., 1., 2.],[6., 7., 3., 0.],[4., 5., 9., 1.]])

A = np.fix((10*(np.random.rand(300, 300))))
B = np.fix((10*(np.random.rand(300, 300))))

In [47]:
%%time
print('A @ B = \n', A @ B)

A @ B = 
 [[5800. 6317. 6119. ... 6273. 6122. 6050.]
 [6668. 6807. 6841. ... 6863. 6416. 6314.]
 [5916. 6556. 6343. ... 6190. 6037. 5933.]
 ...
 [5970. 6437. 6270. ... 6118. 5951. 5844.]
 [6674. 6684. 7087. ... 7010. 6515. 6333.]
 [5849. 6241. 6093. ... 6256. 6015. 5975.]]
CPU times: user 6.36 ms, sys: 1.01 ms, total: 7.37 ms
Wall time: 10.7 ms


In [48]:
%%time
C_standard = mat_mul_standard(A, B)
print('C_standard = \n', C_standard)

C_standard = 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
CPU times: user 3 ms, sys: 997 µs, total: 4 ms
Wall time: 3.11 ms


In [49]:
%%time
C_columns = mat_mul_columns(A, B)
print('C_columns = \n', C_columns)

C_columns = 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
CPU times: user 4.25 ms, sys: 3.02 ms, total: 7.27 ms
Wall time: 12.4 ms


In [50]:
%%time
C_rows = mat_mul_rows(A, B)
print('C_rows = \n', C_rows)

C_rows = 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
CPU times: user 3.49 ms, sys: 992 µs, total: 4.48 ms
Wall time: 5.2 ms


In [51]:
%%time
C_column_times_row = mat_mul_column_times_row(A, B)
print('C_column_times_row = \n', C_column_times_row)

C_column_times_row = 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
CPU times: user 3.6 ms, sys: 7 µs, total: 3.61 ms
Wall time: 2.96 ms
